name: Deploy Aldenium React App to VPS

# Запускать workflow при пуше в ветку main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # 4. Сборка React-приложения <--- ШАГ СБОРКИ
      - name: Build application
        run: npm run build # Эта команда создаст папку 'dist'

      # 4.1 Логирование после сборки <--- ОТДЕЛЬНЫЙ ШАГ ДЛЯ ЛОГА
      - name: List files after build
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in workspace:"
          ls -la ${{ github.workspace }}

      # 5. Деплой на VPS с помощью SSH и rsync
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0 # Рекомендую указать версию, например v1.0.0
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e # !!! Важно: Остановить скрипт при ошибке rsync !!!
            echo "Deploying from ${{ github.workspace }}/dist/ to ${{ secrets.VPS_TARGET_PATH }}/"
            rsync -avz --delete ${{ github.workspace }}/dist/ ${{ secrets.VPS_TARGET_PATH }}/
            echo "Rsync command finished." # Изменено для ясности