name: Deploy Aldenium React App to VPS

# Запускать workflow при пуше в ветку main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # 4. Сборка React-приложения <--- ШАГ СБОРКИ
      - name: Build application
        run: npm run build # Эта команда создаст папку 'dist'

    # 5. Деплой на VPS с помощью rsync
      - name: Deploy to VPS via rsync
        uses: easingthemes/ssh-deploy@v5.0.0 # Используй актуальную стабильную версию
        with:
          # Приватный SSH ключ для подключения к серверу
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          # Аргументы для rsync (архивный, сжатие, подробный, удалять лишнее на сервере)
          ARGS: "-avz --delete"
          # Локальная папка-источник (относительно корня репозитория)
          # Убедись, что имя совпадает с тем, что создает твоя сборка (обычно 'dist')
          SOURCE: "dist/"
          # Имя пользователя на удаленном сервере
          REMOTE_USER: ${{ secrets.VPS_SSH_USER }}
          # IP адрес или домен удаленного сервера
          REMOTE_HOST: ${{ secrets.VPS_SSH_HOST }}
          # Целевая папка на удаленном сервере
          TARGET: ${{ secrets.VPS_TARGET_PATH }}
          # Можно добавить исключения, если нужно
          # EXCLUDE: "/git/, /node_modules/"